name: BA289
favicon: null
layout_spectrum: 0.0038
typography_spectrum: 0.45985
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#06090e'
    - '#fffeff'
    - '#85b6df'
    - '#4a73a9'
    - '#cad2dd'
  brandStrength: 0
  lightness: 0.340640441281721
  saturation: 0.5625
  rhythmicContrast: 0.9620969616807997
purpose: []
