name: BA289
favicon: null
layout_spectrum: 0.0038
typography_spectrum: 0.45985
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#515151'
    - '#506079'
    - '#979ba6'
    - '#182627'
    - '#303839'
  brandStrength: 0.5
  lightness: 0.340640441281721
  saturation: 0.5625
  rhythmicContrast: 0
purpose: []
